# Core
baseURL                       = "https://techqueria.org/"
buildFuture                   = true
copyright                     = "This work is licensed under MIT."
enableEmoji                   = true
enableInlineShortcodes        = true
enableRobotsTXT               = true
footnoteReturnLinkContents    = "↩"
metaDataFormat                = "yaml"
Paginate                      = 12
PaginatePath                  = ""
publishDir                    = "dist"
title                         = "Techqueria"

# Code Snippets
pygmentsCodefences            = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle                 = "manni"

# Taxonomy
preserveTaxonomyNames         = false

# Language
languageCode                  = "en-US"

# Internal Templates
googleAnalytics               = "UA-88917358-1"
disqusShortname               = "techqueria"

# HTML Renderer
[markup.goldmark.renderer]
    unsafe                    = true

# Categories
[taxonomies]
  tag                         = "tags"
  category                    = "categories"

# Output Formats
[outputs]
    home                      = ["HTML", "AMP", "RSS"]
    page                      = ["HTML", "AMP"]
    section                   = ["HTML", "RSS"]

# RSS
[outputFormats]
    [outputFormats.RSS]
        mediatype             = "application/rss"
        baseName              = "feed"

# SEO
[params]
    description               = "Techqueria is a nonprofit that serves the largest community of Latinx in Tech."
    year                      = 2015
    og_image                  = "https://i.imgur.com/O2YyA3E.png"
    logo                      = "https://i.imgur.com/iJpGY6L.png"
    locale                    = "en_US"
    default_content_language  = "en"
    google_site_verification  = "eopAXVNFciPM1qMa-owNdbQH3PWDZ6bFhrZQDaKbqZ4"

# Social Links
[social]
    email                     = "hola@techqueria.org"
    facebook                  = "techqueria"
    github                    = "techqueria"
    instagram                 = "techqueriaorg"
    linkedin                  = "company/techqueria"
    twitter                   = "Techqueria"
    youtube                   = "UCUhXR0BOgyqrS1E_Sr4PVjQ"

# Permalinks
[permalinks]
  news                        = "/news/:year/:month/:day/:title/"
  events                      = "/events/:year/:month/:day/:title/"

# Author
[author]
    name                      = "Techqueria"
    copyright                 = "©️ Techqueria.org"

# Menu

# Homepage
[[menu.homepage]]
    name                      = "Latinx in Tech"
    url                       = "/"

# About
[[menu.main]]
    name                      = "About"
    url                       = "/about/"
[[menu.main]]
    parent                    = "About"
    name                      = "Brand Guidelines"
    url                       = "/brand/"
[[menu.main]]
    parent                    = "About"
    name                      = "Career Center"
    url                       = "https://techqueria.careerwebsite.com"
[[menu.main]]
    parent                    = "About"
    name                      = "Code of Conduct"
    url                       = "/code-of-conduct/"
[[menu.main]]
    parent                    = "About"
    name                      = "Contact Us"
    url                       = "/contact/"
[[menu.main]]
    parent                    = "About"
    name                      = "No Tech for ICE Policy"
    url                       = "/no-tech-for-ice/"
[[menu.main]]
    parent                    = "About"
    name                      = "Team"
    url                       = "/team/"
[[menu.main]]
    parent                    = "About"
    name                      = "Shop Merch"
    url                       = "/shop/"

# Get Involved
[[menu.main]]
    name                      = "Get Involved"
    url                       = "/join/"
[[menu.main]]
    parent                    = "Get Involved"
    name                      = "Become a Member"
    url                       = "/join/"
    weight                    = 1
[[menu.main]]
    parent                    = "Get Involved"
    name                      = "Become a Speaker"
    url                       = "/speak/"
    weight                    = 2
[[menu.main]]
    parent                    = "Get Involved"
    name                      = "Become a Volunteer"
    url                       = "/volunteer/"
    weight                    = 3
[[menu.main]]
    parent                    = "Get Involved"
    name                      = "Become a Chapter Director"
    url                       = "/chapter-director/"
    weight                    = 4
[[menu.main]]
    parent                    = "Get Involved"
    name                      = "Submit Your Resume"
    url                       = "/submit-resume/"
    weight                    = 5
[[menu.main]]
    parent                    = "Get Involved"
    name                      = "Submit Your Testimonial"
    url                       = "/submit-testimonial/"
    weight                    = 6

# Communities
[[menu.main]]
    name                      = "Communities"
    url                       = "/communities/"
[[menu.main]]
    parent                    = "Communities"
    name                      = "Email Newsletter"
    url                       = "/subscribe/"
[[menu.main]]
    parent                    = "Communities"
    name                      = "Facebook Group"
    url                       = "https://www.facebook.com/groups/techqueria"
[[menu.main]]
    parent                    = "Communities"
    name                      = "Facebook Page"
    url                       = "https://www.facebook.com/techqueria"
[[menu.main]]
    parent                    = "Communities"
    name                      = "Google Business"
    url                       = "https://g.page/Techqueria?we"
[[menu.main]]
    parent                    = "Communities"
    name                      = "Instagram"
    url                       = "https://instagram.com/techqueriaorg"
[[menu.main]]
    parent                    = "Communities"
    name                      = "GitHub Organization"
    url                       = "https://github.com/techqueria"
[[menu.main]]
    parent                    = "Communities"
    name                      = "LinkedIn Group"
    url                       = "https://www.linkedin.com/groups/13500636"
[[menu.main]]
    parent                    = "Communities"
    name                      = "LinkedIn Page"
    url                       = "https://www.linkedin.com/company/techqueria/"
[[menu.main]]
    parent                    = "Communities"
    name                      = "Pinterest"
    url                       = "https://pinterest.com/techqueria"
[[menu.main]]
    parent                    = "Communities"
    name                      = "Slack Workspace"
    url                       = "/communities/slack/"
[[menu.main]]
    parent                    = "Communities"
    name                      = "Twitter"
    url                       = "https://twitter.com/Techqueria"
[[menu.main]]
    parent                    = "Communities"
    name                      = "YouTube Channel"
    url                       = "https://www.youtube.com/c/Techqueria"

# Donate
[[menu.main]]
    name                      = "Donate"
    url                       = "/donate/"
[[menu.main]]
    parent                    = "Donate"
    name                      = "Become a Patron"
    url                       = "https://www.patreon.com/techqueria"
[[menu.main]]
    parent                    = "Donate"
    name                      = "Donate Space"
    url                       = "/donate/donate-space/"
[[menu.main]]
    parent                    = "Donate"
    name                      = "Match Your Gift"
    url                       = "/donate/match-your-gift/"

# Events
[[menu.main]]
    name                      = "Events"
    url                       = "https://events.techqueria.org/virtual-events/"
    externalLink              = false
[[menu.main]]
    parent                    = "Events"
    name                      = "#LHM Summit 2020"
    url                       = "/summit/"
    weight                    = 1
[[menu.main]]
    parent                    = "Events"
    name                      = "Upcoming Events"
    url                       = "https://events.techqueria.org/events"
    weight                    = 2
[[menu.main]]
    parent                    = "Events"
    name                      = "Chapters"
    url                       = "/chapters/"
    weight                    = 4
[[menu.main]]
    parent                    = "Events"
    name                      = "Community Calendar"
    url                       = "/community-calendar/"
    weight                    = 5

# News
[[menu.main]]
    name                      = "News"
    url                       = "/news/"
[[menu.main]]
    parent                    = "News"
    name                      = "Techqueria Podcast"
    url                       = "/podcast/"
[[menu.main]]
    parent                    = "News"
    name                      = "Resources"
    url                       = "/resources/"
[[menu.main]]
    parent                    = "News"
    name                      = "Testimonials"
    url                       = "/testimonials/"

# Support Us
[[menu.main]]
    name                      = "Partner"
    url                       = "/partner/"
[[menu.main]]
    parent                    = "Partner"
    name                      = "Partnerships Deck"
    url                       = "/partner/#partnerships-deck"
    weight                    = 1
[[menu.main]]
    parent                    = "Partner"
    name                      = "Purchase a CTA"
    url                       = "/partner/#purchase-a-cta"
    weight                    = 2
[[menu.main]]
    parent                    = "Partner"
    name                      = "Submit a Partnership Inquiry"
    url                       = "/partner/#submit-a-partnership-inquiry"
    weight                    = 3
[[menu.main]]
    parent                    = "Partner"
    name                      = "Our Supporters"
    url                       = "/supporters/"
    weight                    = 4

# Social Menu
[[menu.social]]
    name                      = "Twitter"
    url                       = "https://twitter.com/Techqueria"
    identifier                = "fab fa-lg fa-twitter"
    weight                    = 1
[[menu.social]]
    name                      = "LinkedIn"
    url                       = "https://www.linkedin.com/company/techqueria/"
    identifier                = "fab fa-lg fa-linkedin"
    weight                    = 2

# Slack Menu
[[menu.portal]]
    name                      = "Join Us"
    url                       = "/join/"
    identifier                = "fab fa-lg fa-slack"
[[menu.portal]]
    name                      = "Login"
    url                       = "https://techqueria.slack.com"
    identifier                = "fas fa-lg fa-sign-in-alt"
