# Core
baseURL                    = "https://techqueria.org/"
buildFuture                = true
copyright                  = "This work is licensed under MIT."
enableEmoji                = true
enableRobotsTXT            = true
enableInlineShortcodes     = true
footnoteReturnLinkContents = "↩"
metaDataFormat             = "yaml"
title                      = "Techqueria"
publishDir                 = "dist"
Paginate                   = 12
PaginatePath               = ""

# Language
languageCode                         = "en-US"
DefaultContentLanguage               = "en"
enableMissingTranslationPlaceholders = true

# English then Español
[languages]
  [languages.en]
    languageName = "English"
    contentDir   = "content/english"
    weight       = 1
  [languages.es]
    languageName = "Español"
    contentDir   = "content/espanol"
    weight       = 2
    [languages.es.params]
      description = "Techqueria es una organización sin fines de lucro que representa una de las comunidades más grandes para profesionales de Latinx en la industria tecnológica."
      og_image    = "https://i.imgur.com/T0sg75l.png"

# Categories
preserveTaxonomyNames = false

[taxonomies]
  tag      = "tags"
  category = "categories"

# Code
pygmentsCodefences            = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle                 = "manni"

# Internal Templates
googleAnalytics = "UA-88917358-1"
disqusShortname = "techqueria"

# Output Formats
[outputs]
    home = ["HTML", "AMP", "RSS"]
    page = ["HTML", "AMP"]

# RSS
[outputFormats]
    [outputFormats.RSS]
        mediatype = "application/rss"
        baseName  = "feed"

# SEO
[params]
    description              = "Techqueria is a nonprofit that serves the largest community of Latinx in Tech."
    year                     = 2015
    og_image                 = "https://i.imgur.com/O2YyA3E.png"
    logo                     = "https://i.imgur.com/iJpGY6L.png"
    locale                   = "en_US"
    default_content_language = "en"
    google_site_verification = "eopAXVNFciPM1qMa-owNdbQH3PWDZ6bFhrZQDaKbqZ4"
    phraseAppEnabled         = true
    phraseapp_key            = "{{__phrase_%s__}}"

# Social Links
[social]
    email     = "organizers@techqueria.org"
    facebook  = "techqueria"
    github    = "techqueria"
    instagram = "techqueriaorg"
    linkedin  = "company/techqueria"
    meetup    = "techqueria"
    twitter   = "Techqueria"
    youtube   = "UCUhXR0BOgyqrS1E_Sr4PVjQ"

# Permalinks
[permalinks]
  news   = "/news/:year/:month/:day/:title/"
  events = "/events/:year/:month/:day/:title/"

# Author
[author]
    name      = "Techqueria"
    copyright = "©️ Techqueria.org"

# Menu

# Homepage
[[menu.homepage]]
    name = "Latinx in Tech"
    url  = "/"

# About
[[menu.main]]
    name = "About"
    url  = "/about/"
[[menu.main]]
    parent = "About"
    name   = "Brand"
    url    = "/about/brand/"
[[menu.main]]
    parent = "About"
    name   = "Contact"
    url    = "/about/contact/"
[[menu.main]]
    parent = "About"
    name   = "Events"
    url    = "/events/"
[[menu.main]]
    parent = "About"
    name   = "Team"
    url    = "/team/"
[[menu.main]]
    parent = "About"
    name   = "Shop"
    url    = "/about/shop/"

# Communities
[[menu.main]]
    name = "Communities"
    url  = "/communities/"
[[menu.main]]
    parent = "Communities"
    name   = "City Chapters"
    url    = "/communities/chapters/"
[[menu.main]]
    parent = "Communities"
    name   = "Eventbrite"
    url    = "https://techqueria.eventbrite.com"
[[menu.main]]
    parent = "Communities"
    name   = "Facebook Group"
    url    = "https://www.facebook.com/groups/techqueria"
[[menu.main]]
    parent = "Communities"
    name   = "Facebook Page"
    url    = "https://www.facebook.com/techqueria"
[[menu.main]]
    parent = "Communities"
    name   = "GitHub Organization"
    url    = "https://github.com/techqueria"
[[menu.main]]
    parent = "Communities"
    name   = "LinkedIn Group"
    url    = "https://www.linkedin.com/groups/13500636"
[[menu.main]]
    parent = "Communities"
    name   = "LinkedIn Page"
    url    = "https://www.linkedin.com/company/techqueria/"
[[menu.main]]
    parent = "Communities"
    name   = "Meetup Group"
    url    = "https://www.meetup.com/techqueria/"
[[menu.main]]
    parent = "Communities"
    name   = "Newsletter"
    url    = "https://mailchi.mp/c12256627e10/techqueria-newsletter"
[[menu.main]]
    parent = "Communities"
    name   = "Slack Workspace"
    url    = "/communities/slack/"
[[menu.main]]
    parent = "Communities"
    name   = "Twitter"
    url    = "https://twitter.com/Techqueria"
[[menu.main]]
    parent = "Communities"
    name   = "YouTube Channel"
    url    = "https://www.youtube.com/channel/UCUhXR0BOgyqrS1E_Sr4PVjQ"

# Donate
[[menu.main]]
    name = "Donate"
    url  = "/donate/"
[[menu.main]]
    parent = "Donate"
    name   = "Contribute through Open Collective"
    url    = "https://opencollective.com/techqueria"
[[menu.main]]
    parent = "Donate"
    name   = "Contribute through Patreon"
    url    = "https://www.patreon.com/techqueria"
[[menu.main]]
    parent = "Donate"
    name   = "Contribute through Amazon Smile"
    url    = "https://smile.amazon.com/ch/83-2656715"

# Events
[[menu.main]]
    name = "Events"
    url  = "/events/"
[[menu.main]]
    parent = "Events"
    name   = "Become a Speaker"
    url    = "/support-us/speak/"
[[menu.main]]
    parent = "Events"
    name   = "Community Calendar"
    url    = "/events/#community-calendar"
[[menu.main]]
    parent = "Events"
    name   = "Donate Space"
    url    = "/support-us/donate-space/"

# Resources
[[menu.main]]
    name = "News"
    url  = "/news/"

# Resources
[[menu.main]]
    name = "Resources"
    url  = "/resources/"

# Support Us
[[menu.main]]
    name = "Support Us"
    url  = "/support-us/"
[[menu.main]]
    parent = "Support Us"
    name   = "Become a Sponsor"
    url    = "/support-us/#sponsorship-packages"
[[menu.main]]
    parent = "Support Us"
    name   = "Become a Volunteer"
    url    = "/support-us/volunteer/"
[[menu.main]]
    parent = "Support Us"
    name   = "Our Supporters"
    url    = "/supporters/"

# TODO: Add gated content navbar links
# Gated Content
# Jobs
# Casa (Member Portal)
# Login/Sign Up

# Social Menu
[[menu.social]]
    name       = "Twitter"
    url        = "https://twitter.com/Techqueria"
    identifier = "fab fa-lg fa-twitter"
    weight     = 1
[[menu.social]]
    name       = "LinkedIn"
    url        = "https://www.linkedin.com/company/techqueria/"
    identifier = "fab fa-lg fa-linkedin"
    weight     = 2

# Slack Menu
[[menu.slack]]
    name       = "Join our Slack"
    url        = "https://goo.gl/forms/VRARl4qkkLj3BJLl1"
    identifier = "fab fa-lg fa-slack"
[[menu.slack]]
    name       = "Login to Slack"
    url        = "https://techqueria.slack.com"
    identifier = "fas fa-lg fa-sign-in-alt"

# Menu - Español

# Homepage
[[languages.es.menu.homepage]]
    name = "Latinx en Tecnología"
    url  = "/"

# About
[[languages.es.menu.main]]
    name = "Sobre nosotros"
    url  = "/about/"
[[languages.es.menu.main]]
    parent = "Sobre nosotros"
    name   = "Marca"
    url    = "/about/brand/"
[[languages.es.menu.main]]
    parent = "Sobre nosotros"
    name   = "Contacto"
    url    = "/about/contact/"
[[languages.es.menu.main]]
    parent = "Sobre nosotros"
    name   = "Eventos"
    url    = "/events/"
[[languages.es.menu.main]]
    parent = "Sobre nosotros"
    name   = "Equipo"
    url    = "/team/"
[[languages.es.menu.main]]
    parent = "Sobre nosotros"
    name   = "Tienda"
    url    = "/about/shop/"

# Communities
[[languages.es.menu.main]]
    name = "Comunidades"
    url  = "/communities/"
[[languages.es.menu.main]]
    parent = "Comunidades"
    name   = "Capítulos de la Ciudad"
    url    = "/communities/chapters/"
[[languages.es.menu.main]]
    parent = "Comunidades"
    name   = "Eventbrite"
    url    = "https://techqueria.eventbrite.com"
[[languages.es.menu.main]]
    parent = "Comunidades"
    name   = "Grupo de Facebook"
    url    = "https://www.facebook.com/groups/techqueria"
[[languages.es.menu.main]]
    parent = "Comunidades"
    name   = "Página de Facebook"
    url    = "https://www.facebook.com/techqueria"
[[languages.es.menu.main]]
    parent = "Comunidades"
    name   = "Organización de GitHub"
    url    = "https://github.com/techqueria"
[[languages.es.menu.main]]
    parent = "Comunidades"
    name   = "Grupo de LinkedIn"
    url    = "https://www.linkedin.com/groups/13500636"
[[languages.es.menu.main]]
    parent = "Comunidades"
    name   = "Página de LinkedIn"
    url    = "https://www.linkedin.com/company/techqueria/"
[[languages.es.menu.main]]
    parent = "Comunidades"
    name   = "Grupo de Meetup"
    url    = "https://www.meetup.com/techqueria/"
[[languages.es.menu.main]]
    parent = "Comunidades"
    name   = "Boletín electrónico"
    url    = "https://mailchi.mp/c12256627e10/techqueria-newsletter"
[[languages.es.menu.main]]
    parent = "Comunidades"
    name   = "Espacio de trabajo en Slack"
    url    = "/communities/slack/"
[[languages.es.menu.main]]
    parent = "Comunidades"
    name   = "Twitter"
    url    = "https://twitter.com/Techqueria"
[[languages.es.menu.main]]
    parent = "Comunidades"
    name   = "Canal de YouTube"
    url    = "https://www.youtube.com/channel/UCUhXR0BOgyqrS1E_Sr4PVjQ"

# Donate
[[languages.es.menu.main]]
    name = "Donar"
    url  = "/donate/"
[[languages.es.menu.main]]
    parent = "Donar"
    name   = "Contribuir en Open Collective"
    url    = "https://opencollective.com/techqueria/"
[[languages.es.menu.main]]
    parent = "Donar"
    name   = "Contribuir en Patreon"
    url    = "https://www.patreon.com/techqueria"
[[languages.es.menu.main]]
    parent = "Donar"
    name   = "Contribuir en Amazon Smile"
    url    = "https://smile.amazon.com/ch/83-2656715/"

# Resources
[[languages.es.menu.main]]
    name = "Noticias"
    url  = "/news/"

[[languages.es.menu.main]]
    name = "Apoyanos"
    url  = "/support-us/"
[[languages.es.menu.main]]
    parent = "Apoyanos"
    name   = "Hazte Voluntario"
    url    = "/support-us/volunteer/"
[[languages.es.menu.main]]
    parent = "Apoyanos"
    name   = "Donar Espacio"
    url    = "/support-us/donate-space/"
[[languages.es.menu.main]]
    parent = "Apoyanos"
    name   = "Nuestros Partidarios"
    url    = "/supporters/"

[[languages.es.menu.social]]
    name       = "LinkedIn"
    url        = "https://www.linkedin.com/company/techqueria/"
    identifier = "fab fa-lg fa-linkedin"

[[languages.es.menu.social]]
    name       = "Twitter"
    url        = "https://twitter.com/Techqueria"
    identifier = "fab fa-lg fa-twitter"

# Slack Menu

[[languages.es.menu.slack]]
    name       = "Únete a nuestro Slack"
    url        = "https://goo.gl/forms/VRARl4qkkLj3BJLl1"
    identifier = "fab fa-lg fa-slack"

[[languages.es.menu.slack]]
    name       = "Iniciar sesión en Slack"
    url        = "https://techqueria.slack.com"
    identifier = "fas fa-lg fa-sign-in-alt"
