[build]
  publish = "dist"
  command = "gulp build"
[build.environment]
  TZ = "America/Los_Angeles"
  tz = "America/Los_Angeles"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
