baseURL                       = "https://techqueria.org/"
title                         = "Techqueria"
metaDataFormat                = "yaml"
enableEmoji                   = true
footnoteReturnLinkContents    = "‚Ü©"

# Language
languageCode                  = "en-us"
defaultContentLanguage        = "en"

# Categories
preserveTaxonomyNames         = false

# Code
pygmentsCodefences            = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle                 = "manni"

# Internal Templates
# googleAnalytics             = ""
# disqusShortname             = ""

# RSS
[outputs]
    home                      = ["HTML", "RSS"]
    page                      = ["HTML"]

[outputFormats]
    [outputFormats.RSS]
        mediatype             = "application/rss"
        baseName              = "feed"

# SEO
[params]
    description               = "We're a community of Latinx professionals in the tech industry. üåÆÔ∏è This space aims to be inclusive so we invite Latinx from the regions of the Caribbean, Haiti, and Brazil as well as those who identify as Afro-Latinx or LGBTQ. The term Latinx is used instead of Latino because it is a gender-neutral and inclusive term."
    copyright                 = "Techqueria.org"
    year                      = 2016
    og_image                  = "https://i.imgur.com/ONfQqEV.png"
    logo                      = "https://i.imgur.com/iJpGY6L.png"

# Permalinks
[permalinks]
  blog                        = "/blog/:year/:month/:day/:title/"
  testimonials                = "/testimonials/:year/:month/:day/:title/"
  press                       = "/press/:year/:month/:day/:title/"

[author]
    name                      = "Techqueria"
    copyright                 = "¬©Ô∏è Techqueria.org"

[[menu.mobile]]
    name                      = "Facebook"
    url                       = "https://www.facebook.com/groups/techqueria"
    identifier                = "fab fa-lg fa-facebook"

[[menu.mobile]]
    name                      = "Twitter"
    url                       = "https://twitter.com/techqueriasf"
    identifier                = "fab fa-lg fa-twitter"

[[menu.left]]
    name                      = "About"
    url                       = "/about/"
    # identifier              = "fas fa-info-circle"

[[menu.left]]
    parent                    = "About"
    name                      = "Photos"
    url                       = "/resources/photos/"

[[menu.left]]
    parent                    = "About"
    name                      = "Brand"
    url                       = "/resources/brand/"

[[menu.left]]
    parent                    = "About"
    name                      = "Code of Conduct"
    url                       = "/resources/code-of-conduct/"

[[menu.left]]
    name                      = "Communities"
    url                       = "/communities/"
    # identifier              = "fas fa-comments"

[[menu.left]]
    name                      = "Contact"
    url                       = "/contact/"
    # identifier              = "fas fa-envelope"

[[menu.left]]
    name                      = "Events"
    url                       = "/events/"
    # identifier              = "fas fa-calendar-alt"

[[menu.left]]
    name                      = "Sponsors"
    url                       = "/sponsors/"

[[menu.left]]
    name                      = "Resources"
    url                       = "/resources/"

[[menu.left]]
    parent                    = "Resources"
    name                      = "Career Growth"
    url                       = "/resources/career/"

[[menu.left]]
    parent                    = "Resources"
    name                      = "Design"
    url                       = "/resources/design/"

[[menu.left]]
    parent                    = "Resources"
    name                      = "Health"
    url                       = "/resources/health/"

[[menu.left]]
    parent                    = "Resources"
    name                      = "Immigration"
    url                       = "/resources/immigration/"

[[menu.left]]
    parent                    = "Resources"
    name                      = "Legal"
    url                       = "/resources/legal/"

[[menu.left]]
    parent                    = "Resources"
    name                      = "Open-source"
    url                       = "/resources/open-source/"


[[menu.right]]
    name                      = "Facebook"
    url                       = "https://www.facebook.com/groups/techqueria"
    identifier                = "fab fa-lg fa-facebook"

[[menu.right]]
    name                      = "Twitter"
    url                       = "https://twitter.com/techqueriasf"
    identifier                = "fab fa-lg fa-twitter"
